name: Deploy Dockerized Backend and DockerHub to Azure

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy Docker Image to Azure App Service

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: debugging
      run: |
        echo "Registry URL: ${{ secrets.REGISTRY_URL }}"
        echo "Image Name: ${{ secrets.IMAGE_NAME }}"
        echo "Azure Backend Publish Profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}"
        echo "Registry Username: ${{ secrets.REGISTRY_USERNAME }}"
        echo "Registry Password: ${{ secrets.REGISTRY_PASSWORD }}"
       
    # Login to DockerHub or ACR
    - name: Log in to Docker registry
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    # Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:latest ./backend

    # Push Docker image to registry
    - name: Push Docker image
      run: docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:latest

    # Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: shmms-backend
        publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
        images: ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:latest
